// ==== Полный массив 78 карт Таро ====
const cards = [
    // ===== Кубки (Женя) =====
    { name:"Ace of Cups", image:"cards/cups/ace_cups.jpeg", suit:"cups", meanings:{general:"Новый эмоциональный старт", love:"Новые чувства", work:"Творческий проект", yesno:"Да"}, advice:"Совет от Жени: будь открыта новым эмоциям"},
    { name:"Two of Cups", image:"cards/cups/two_cups.jpeg", suit:"cups", meanings:{general:"Партнерство и гармония", love:"Союз с кем-то особенным", work:"Сотрудничество", yesno:"Да"}, advice:"Совет от Жени: доверяй партнеру"},
    { name:"Three of Cups", image:"cards/cups/three_cups.jpeg", suit:"cups", meanings:{general:"Радость и встречи", love:"Весёлые свидания", work:"Командная работа", yesno:"Да"}, advice:"Совет от Жени: радуйся мелочам"},
    { name:"Four of Cups", image:"cards/cups/four_cups.jpeg", suit:"cups", meanings:{general:"Размышления и скука", love:"Не замечаешь нового", work:"Отдых нужен", yesno:"Нет"}, advice:"Совет от Жени: присмотрись внимательнее"},
    { name:"Five of Cups", image:"cards/cups/five_cups.jpeg", suit:"cups", meanings:{general:"Потери и сожаления", love:"Разочарование", work:"Ошибка в проекте", yesno:"Нет"}, advice:"Совет от Жени: смотри вперед"},
    { name:"Six of Cups", image:"cards/cups/six_cups.jpeg", suit:"cups", meanings:{general:"Ностальгия и воспоминания", love:"Старые чувства", work:"Опыт помогает", yesno:"Да"}, advice:"Совет от Жени: цени прошлое"},
    { name:"Seven of Cups", image:"cards/cups/seven_cups.jpeg", suit:"cups", meanings:{general:"Выбор и мечты", love:"Иллюзии", work:"Много вариантов", yesno:"Нет"}, advice:"Совет от Жени: выбирай разумно"},
    { name:"Eight of Cups", image:"cards/cups/eight_cups.jpeg", suit:"cups", meanings:{general:"Отход и поиск", love:"Оставь прошлое", work:"Поменяй стратегию", yesno:"Нет"}, advice:"Совет от Жени: двигайся дальше"},
    { name:"Nine of Cups", image:"cards/cups/nine_cups.jpeg", suit:"cups", meanings:{general:"Исполнение желаний", love:"Счастье в отношениях", work:"Успех проекта", yesno:"Да"}, advice:"Совет от Жени: наслаждайся моментом"},
    { name:"Ten of Cups", image:"cards/cups/ten_cups.jpeg", suit:"cups", meanings:{general:"Семейное счастье", love:"Гармония и радость", work:"Завершение цикла", yesno:"Да"}, advice:"Совет от Жени: цени семью"},
    { name:"Page of Cups", image:"cards/cups/page_cups.jpeg", suit:"cups", meanings:{general:"Новые эмоции", love:"Маленькая радость", work:"Творческий всплеск", yesno:"Да"}, advice:"Совет от Жени: будь открыта новым возможностям"},
    { name:"Knight of Cups", image:"cards/cups/khight_cups.jpeg", suit:"cups", meanings:{general:"Романтичные действия", love:"Ухаживание", work:"Проявление инициативы", yesno:"Да"}, advice:"Совет от Жени: действуй с сердцем"},
    { name:"Queen of Cups", image:"cards/cups/queen_cups.jpeg", suit:"cups", meanings:{general:"Эмоциональная мудрость", love:"Поддержка партнера", work:"Интуиция помогает", yesno:"Да"}, advice:"Совет от Жени: слушай свои чувства"},
    { name:"King of Cups", image:"cards/cups/king_cups.jpeg", suit:"cups", meanings:{general:"Контроль эмоций", love:"Стабильность в любви", work:"Лидерство в проекте", yesno:"Да"}, advice:"Совет от Жени: держи баланс эмоций"},

    // ===== Пентакли (Настя) =====
    { name:"Ace of Pentacles", image:"cards/pentacles/ace_pentacles.jpeg", suit:"pentacles", meanings:{general:"Новый материальный шанс", love:"Стабильность в отношениях", work:"Новый доход", yesno:"Да"}, advice:"Совет от Насти: используй возможности"},
    { name:"Two of Pentacles", image:"cards/pentacles/two_pentacles.jpeg", suit:"pentacles", meanings:{general:"Баланс и гибкость", love:"Сохраняй гармонию", work:"Управляй задачами", yesno:"Да"}, advice:"Совет от Насти: расставляй приоритеты"},
    { name:"Three of Pentacles", image:"cards/pentacles/three_pentacles.jpeg", suit:"pentacles", meanings:{general:"Командная работа", love:"Поддержка партнера", work:"Совместный проект", yesno:"Да"}, advice:"Совет от Насти: цени команду"},
    { name:"Four of Pentacles", image:"cards/pentacles/four_pentacles.jpeg", suit:"pentacles", meanings:{general:"Сохранение ресурсов", love:"Осторожность в любви", work:"Контроль бюджета", yesno:"Нет"}, advice:"Совет от Насти: не бойся делиться"},
    { name:"Five of Pentacles", image:"cards/pentacles/five_pentacles.jpeg", suit:"pentacles", meanings:{general:"Трудности и лишения", love:"Отсутствие поддержки", work:"Проблемы с финансами", yesno:"Нет"}, advice:"Совет от Насти: ищи помощь"},
    { name:"Six of Pentacles", image:"cards/pentacles/six_pentacles.jpeg", suit:"pentacles", meanings:{general:"Щедрость и помощь", love:"Баланс в отношениях", work:"Поддержка коллег", yesno:"Да"}, advice:"Совет от Насти: помогай и получай помощь"},
    { name:"Seven of Pentacles", image:"cards/pentacles/seven_pentacles.jpeg", suit:"pentacles", meanings:{general:"Ожидание результатов", love:"Обдумай отношения", work:"Оценка работы", yesno:"Да"}, advice:"Совет от Насти: проявляй терпение"},
    { name:"Eight of Pentacles", image:"cards/pentacles/eight_pentacles.jpeg", suit:"pentacles", meanings:{general:"Усердная работа", love:"Работай над отношениями", work:"Повышай мастерство", yesno:"Да"}, advice:"Совет от Насти: совершенствуй навыки"},
    { name:"Nine of Pentacles", image:"cards/pentacles/nine_pentacles.jpeg", suit:"pentacles", meanings:{general:"Самостоятельность", love:"Независимость в любви", work:"Финансовая стабильность", yesno:"Да"}, advice:"Совет от Насти: цени свою независимость"},
    { name:"Ten of Pentacles", image:"cards/pentacles/ten_pentacles.jpeg", suit:"pentacles", meanings:{general:"Материальный успех", love:"Семейное счастье", work:"Завершение проекта", yesno:"Да"}, advice:"Совет от Насти: сохраняй наследие"},
    { name:"Page of Pentacles", image:"cards/pentacles/page_pentacles.jpeg", suit:"pentacles", meanings:{general:"Учение и возможности", love:"Любопытство в отношениях", work:"Новые навыки", yesno:"Да"}, advice:"Совет от Насти: изучай новое"},
    { name:"Knight of Pentacles", image:"cards/pentacles/knight_pentacles.jpeg", suit:"pentacles", meanings:{general:"Стабильность и настойчивость", love:"Верность и забота", work:"Постепенный прогресс", yesno:"Да"}, advice:"Совет от Насти: будь терпеливой"},
    { name:"Queen of Pentacles", image:"cards/pentacles/queen_pentacles.jpeg", suit:"pentacles", meanings:{general:"Практичность и забота", love:"Забота о партнере", work:"Организация и эффективность", yesno:"Да"}, advice:"Совет от Насти: заботься о доме и работе"},
    { name:"King of Pentacles", image:"cards/pentacles/king_pentacles.jpeg", suit:"pentacles", meanings:{general:"Финансовая стабильность", love:"Стабильный партнер", work:"Лидерство и успех", yesno:"Да"}, advice:"Совет от Насти: управляй ресурсами разумно"},

    // ===== Мечи (Маша) =====
    { name:"Ace of Swords", image:"cards/swords/ace_swords.jpeg", suit:"swords", meanings:{general:"Новая идея", love:"Честность в отношениях", work:"Прояснение ситуации", yesno:"Да"}, advice:"Совет от Маши: используй разум"},
    { name:"Two of Swords", image:"cards/swords/two_swords.jpeg", suit:"swords", meanings:{general:"Выбор и сомнение", love:"Неясность в отношениях", work:"Принятие решений", yesno:"Нет"}, advice:"Совет от Маши: прислушайся к логике"},
    { name:"Three of Swords", image:"cards/swords/three_swords.jpeg", suit:"swords", meanings:{general:"Боль и разочарование", love:"Разрыв или ссора", work:"Проблемы с коллегами", yesno:"Нет"}, advice:"Совет от Маши: не зацикливайся на прошлом"},
    { name:"Four of Swords", image:"cards/swords/four_swords.jpeg", suit:"swords", meanings:{general:"Отдых и восстановление", love:"Пауза в отношениях", work:"Отдых после работы", yesno:"Да"}, advice:"Совет от Маши: дай себе время"},
    { name:"Five of Swords", image:"cards/swords/five_swords.jpeg", suit:"swords", meanings:{general:"Конфликты и потери", love:"Ссоры и недопонимание", work:"Столкновение интересов", yesno:"Нет"}, advice:"Совет от Маши: избегай ссор"},
    { name:"Six of Swords", image:"cards/swords/six_swords.jpeg", suit:"swords", meanings:{general:"Переход и перемены", love:"Переход к новому", work:"Перемещение или смена работы", yesno:"Да"}, advice:"Совет от Маши: двигайся вперед"},
    { name:"Seven of Swords", image:"cards/swords/seven_swords.jpeg", suit:"swords", meanings:{general:"Хитрость и осторожность", love:"Будь внимательна к людям", work:"Не раскрывай все карты", yesno:"Нет"}, advice:"Совет от Маши: действуй скрытно"},
    { name:"Eight of Swords", image:"cards/swords/eight_swords.jpeg", suit:"swords", meanings:{general:"Ограничения", love:"Чувство ловушки", work:"Ограничения и препятствия", yesno:"Нет"}, advice:"Совет от Маши: ищи выход"},
    { name:"Nine of Swords", image:"cards/swords/nine_swords.jpeg", suit:"swords", meanings:{general:"Беспокойство", love:"Страх потерять", work:"Стресс и тревога", yesno:"Нет"}, advice:"Совет от Маши: сохраняй спокойствие"},
    { name:"Ten of Swords", image:"cards/swords/ten_swords.jpeg", suit:"swords", meanings:{general:"Конец цикла", love:"Разрыв отношений", work:"Проблема завершена", yesno:"Нет"}, advice:"Совет от Маши: принимай конец"},
    { name:"Page of Swords", image:"cards/swords/page_swords.jpeg", suit:"swords", meanings:{general:"Любопытство и обучение", love:"Новые знакомства", work:"Учись новому", yesno:"Да"}, advice:"Совет от Маши: будь наблюдательной"},
    { name:"Knight of Swords", image:"cards/swords/knight_swords.jpeg", suit:"swords", meanings:{general:"Быстрые действия", love:"Стремительные чувства", work:"Резкие решения", yesno:"Да"}, advice:"Совет от Маши: действуй быстро, но обдуманно"},
    { name:"Queen of Swords", image:"cards/swords/queen_swords.jpeg", suit:"swords", meanings:{general:"Интеллект и проницательность", love:"Честность в чувствах", work:"Анализ и стратегия", yesno:"Да"}, advice:"Совет от Маши: будь мудрой и честной"},
    { name:"King of Swords", image:"cards/swords/king_swords.jpeg", suit:"swords", meanings:{general:"Лидерство и логика", love:"Стабильность в чувствах", work:"Контроль и решения", yesno:"Да"}, advice:"Совет от Маши: действуй разумно"},

    // ===== Жезлы (Дарина) =====
    { name:"Ace of Wands", image:"cards/wands/ace_wands.jpeg", suit:"wands", meanings:{general:"Новая энергия", love:"Инициатива в любви", work:"Начало проекта", yesno:"Да"}, advice:"Совет от Дарины: действуй смело"},
    { name:"Two of Wands", image:"cards/wands/two_wands.jpeg", suit:"wands", meanings:{general:"Планирование", love:"Обдумай шаги", work:"Стратегия", yesno:"Да"}, advice:"Совет от Дарины: строй планы"},
    { name:"Three of Wands", image:"cards/wands/three_wands.jpeg", suit:"wands", meanings:{general:"Расширение и рост", love:"Развитие отношений", work:"Выход на новые уровни", yesno:"Да"}, advice:"Совет от Дарины: смело двигайся вперед"},
    { name:"Four of Wands", image:"cards/wands/four_wands.jpeg", suit:"wands", meanings:{general:"Стабильность и праздник", love:"Радость в любви", work:"Успешный проект", yesno:"Да"}, advice:"Совет от Дарины: радуйся достижениям"},
    { name:"Five of Wands", image:"cards/wands/five_wands.jpeg", suit:"wands", meanings:{general:"Конфликт и конкуренция", love:"Разногласия", work:"Соперничество", yesno:"Нет"}, advice:"Совет от Дарины: не вступай в споры"},
    { name:"Six of Wands", image:"cards/wands/six_wands.jpeg", suit:"wands", meanings:{general:"Признание и успех", love:"Взаимные чувства", work:"Победа в проекте", yesno:"Да"}, advice:"Совет от Дарины: наслаждайся успехом"},
    { name:"Seven of Wands", image:"cards/wands/seven_wands.jpeg", suit:"wands", meanings:{general:"Защита позиции", love:"Отстаивай чувства", work:"Борьба за идеи", yesno:"Да"}, advice:"Совет от Дарины: будь настойчивой"},
    { name:"Eight of Wands", image:"cards/wands/eight_wands.jpeg", suit:"wands", meanings:{general:"Быстрое движение", love:"Романтичные события", work:"Скорые решения", yesno:"Да"}, advice:"Совет от Дарины: используй момент"},
    { name:"Nine of Wands", image:"cards/wands/nine_wands.jpeg", suit:"wands", meanings:{general:"Выносливость", love:"Сохраняй чувства", work:"Не сдавайся", yesno:"Да"}, advice:"Совет от Дарины: держись до конца"},
    { name:"Ten of Wands", image:"cards/wands/ten_wands.jpeg", suit:"wands", meanings:{general:"Трудности и нагрузка", love:"Сложности в отношениях", work:"Большая ответственность", yesno:"Нет"}, advice:"Совет от Дарины: делегируй задачи"},
    { name:"Page of Wands", image:"cards/wands/page_wands.jpeg", suit:"wands", meanings:{general:"Любопытство и энтузиазм", love:"Новые знакомства", work:"Новые идеи", yesno:"Да"}, advice:"Совет от Дарины: действуй с энтузиазмом"},
    { name:"Knight of Wands", image:"cards/wands/knight_wands.jpeg", suit:"wands", meanings:{general:"Стремительность и энергия", love:"Смелые поступки", work:"Действуй активно", yesno:"Да"}, advice:"Совет от Дарины: смело двигайся"},
    { name:"Queen of Wands", image:"cards/wands/queen_wands.jpeg", suit:"wands", meanings:{general:"Энергичная и харизматичная", love:"Активно проявляй чувства", work:"Лидер и вдохновитель", yesno:"Да"}, advice:"Совет от Дарины: будь уверенной и харизматичной"},
    { name:"King of Wands", image:"cards/wands/king_wands.jpeg", suit:"wands", meanings:{general:"Сильный и целеустремлённый", love:"Стабильный и решительный", work:"Руководитель проекта", yesno:"Да"}, advice:"Совет от Дарины: веди за собой с уверенностью"},

    // ===== Старшие Арканы (Ника) =====
{ name:"Fool", image:"cards/major/fool.jpeg", suit:"major", meanings:{general:"Начало пути", love:"Свобода в любви", work:"Новые проекты", yesno:"Да"}, advice:"Совет от Ники: будь смелой"},
{ name:"Magician", image:"cards/major/magician.jpeg", suit:"major", meanings:{general:"Сила и ресурсы", love:"Используй свои возможности", work:"Контролируй процесс", yesno:"Да"}, advice:"Совет от Ники: верь в себя"},
{ name:"High Priestess", image:"cards/major/high_priestess.jpeg", suit:"major", meanings:{general:"Интуиция и тайны", love:"Слушай свои чувства", work:"Скрытые возможности", yesno:"Да"}, advice:"Совет от Ники: доверяй интуиции"},
{ name:"Empress", image:"cards/major/empress.jpeg", suit:"major", meanings:{general:"Творчество и забота", love:"Любовь и поддержка", work:"Рост проекта", yesno:"Да"}, advice:"Совет от Ники: будь заботливой"},
{ name:"Emperor", image:"cards/major/emperor.jpeg", suit:"major", meanings:{general:"Стабильность и структура", love:"Надёжность в любви", work:"Лидерство и порядок", yesno:"Да"}, advice:"Совет от Ники: держи контроль"},
{ name:"Hierophant", image:"cards/major/heirophant.jpeg", suit:"major", meanings:{general:"Учение и традиции", love:"Совет и наставление", work:"Следуй правилам", yesno:"Да"}, advice:"Совет от Ники: соблюдай традиции"},
{ name:"Lovers", image:"cards/major/lovers.jpeg", suit:"major", meanings:{general:"Выбор и отношения", love:"Любовь и союз", work:"Сотрудничество", yesno:"Да"}, advice:"Совет от Ники: слушай сердце"},
{ name:"Chariot", image:"cards/major/chariot.jpeg", suit:"major", meanings:{general:"Победа и движение", love:"Действуй активно", work:"Прогресс и успех", yesno:"Да"}, advice:"Совет от Ники: будь решительной"},
{ name:"Strength", image:"cards/major/strength.jpeg", suit:"major", meanings:{general:"Сила духа", love:"Контроль эмоций", work:"Преодоление трудностей", yesno:"Да"}, advice:"Совет от Ники: сохраняй терпение"},
{ name:"Hermit", image:"cards/major/hermit.jpeg", suit:"major", meanings:{general:"Самопознание", love:"Пауза для раздумий", work:"Анализ ситуации", yesno:"Нет"}, advice:"Совет от Ники: ищи внутри себя ответы"},
{ name:"Wheel of Fortune", image:"cards/major/wheel_of_fortune.jpeg", suit:"major", meanings:{general:"Перемены и судьба", love:"Случайные события", work:"Неожиданные возможности", yesno:"Да"}, advice:"Совет от Ники: будь готова к переменам"},
{ name:"Justice", image:"cards/major/justice.jpeg", suit:"major", meanings:{general:"Справедливость", love:"Честность в отношениях", work:"Принятие решений", yesno:"Да"}, advice:"Совет от Ники: будь честной"},
{ name:"Hanged Man", image:"cards/major/hanged_man.jpeg", suit:"major", meanings:{general:"Пауза и переосмысление", love:"Измени подход", work:"Смотри под другим углом", yesno:"Нет"}, advice:"Совет от Ники: смотри шире"},
{ name:"Death", image:"cards/major/death.jpeg", suit:"major", meanings:{general:"Конец и трансформация", love:"Изменения в отношениях", work:"Завершение этапа", yesno:"Нет"}, advice:"Совет от Ники: отпусти старое"},
{ name:"Temperance", image:"cards/major/temperance.jpeg", suit:"major", meanings:{general:"Баланс и гармония", love:"Согласие и компромисс", work:"Сбалансированные решения", yesno:"Да"}, advice:"Совет от Ники: сохраняй равновесие"},
{ name:"Devil", image:"cards/major/devil.jpeg", suit:"major", meanings:{general:"Привязанности и искушения", love:"Опасные связи", work:"Ловушка или соблазн", yesno:"Нет"}, advice:"Совет от Ники: освобождайся от ограничений"},
{ name:"Tower", image:"cards/major/tower.jpeg", suit:"major", meanings:{general:"Резкие перемены", love:"Внезапные разрывы", work:"Кризис в проекте", yesno:"Нет"}, advice:"Совет от Ники: будь готова к неожиданностям"},
{ name:"Star", image:"cards/major/star.jpeg", suit:"major", meanings:{general:"Надежда и вдохновение", love:"Вдохновение в чувствах", work:"Новые идеи", yesno:"Да"}, advice:"Совет от Ники: верь в мечту"},
{ name:"Moon", image:"cards/major/moon.jpeg", suit:"major", meanings:{general:"Иллюзии и интуиция", love:"Не всё ясно", work:"Скрытые риски", yesno:"Нет"}, advice:"Совет от Ники: доверяй интуиции"},
{ name:"Sun", image:"cards/major/sun.jpeg", suit:"major", meanings:{general:"Успех и радость", love:"Счастливые отношения", work:"Успех в работе", yesno:"Да"}, advice:"Совет от Ники: наслаждайся моментом"},
{ name:"Judgement", image:"cards/major/judgement.jpeg", suit:"major", meanings:{general:"Переоценка и пробуждение", love:"Понимание чувств", work:"Пересмотри проекты", yesno:"Да"}, advice:"Совет от Ники: слушай внутренний голос"},
{ name:"World", image:"cards/major/world.jpeg", suit:"major", meanings:{general:"Завершение цикла", love:"Гармония и целостность", work:"Успешное завершение", yesno:"Да"}, advice:"Совет от Ники: празднуй достижения"},



